### ISSUE TITLE
How to get refresh token?

### ISSUE THREAD

**Issue by abdulkader00** [iamLiquidX/AutoAddX#1]
Help me how can I get refresh token?

**Comment by iamLiquidX** [comment]
It can be obtained from rclone config.

**Comment by abdulkader00** [comment]
Got it. If I want to add only to group then is it necessary to fill up client id, secret, token?

**Comment by iamLiquidX** [comment]
This is beta script, so it may or may not work as intended. As i said in readme. I don't have much time to work on this.
